version: '3.8'
services:
  app:
    container_name: nextjs-app
    build: .
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/calendar_on_d_gas
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db

  db:
    container_name: postgres-db
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: calendar_on_d_gas
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
